- name: Ensure necessary software is installed
  apt: 
    name: 
        - bash
        - openssl
        - libssl-dev
    update_cache: yes
    state: latest
  tags: packages

- name: Install Postgres
  apt: 
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    update_cache: true 
    state: present
  tags: packages

- name: check service
  service: 
           name: postgresql 
           state: started 
           enabled: yes
  
- name: Ensure db exists
  become: yes
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_db: 
    name={{ db_name }}
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    template='template0'
    state=present

- name: ensure user has access
  become_user: postgres
  postgresql_user: 
    db={{ db_name }}
    name={{ db_user }}
    password={{ db_password }}
    priv=ALL
    state=present

- name: ensure user doesn't have bad privs
  become_user: postgres
  postgresql_user: 
    name={{ db_user }}
    role_attr_flags=NOSUPERUSER,NOCREATEDB
    state=present
